num1 = float(input("Digite a 1º nota: "))
num2 = float(input("Digite a 2º nota: "))
num3 = float(input("Digite a 3º nota: "))
num4 = float(input("Digite a 4º nota: "))
print(f'A média foi: {(num1+num2+num3+num4)/4:.1f}')