print('Olá, Mundo!')
nome = input('Qual o seu nome?')
print ('Seja bem-vindo', nome,'!')
dia = input('Que dia você nasceu?')
mes = input('Que mês você nasceu?')
ano = input('Que ano você nasceu?')
print ('Olá {},você nasceu {}/{}/{}'.format(nome, dia, mes, ano))